### ISSUE TITLE
Centralize all languages in this feedstock

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/spacy-model-en_core_web-feedstock#13]
All the other languages are looking a little long in the tooth, and are likely susceptible to #11.

It appears all the variants get built from the same upstream `commit`, and therefore presumably are built and uploaded at the same time. There is also a [compatibility matrix](https://github.com/explosion/spacy-models/blob/master/compatibility.json) that gets updated.

It seems like doing the one-time effort to update this feedstock (maybe with a script to refresh when new variants are added) would reduce the overall maintenance burden and provide better service to users.

Ping:
- @conda-forge/spacy-model-de 
- @conda-forge/spacy-model-en_vectors_web
- @conda-forge/spacy-model-es 
- @conda-forge/spacy-model-fr 
- @conda-forge/spacy-model-pt
- @conda-forge/spacy-model-xx
- @conda-forge/spacy-model-nl

**Comment by wolfv** [comment]
awesome!

**Comment by bollwyvl** [comment]
Or do we need a new one through staged recipes, just "spacy-models"?

**Comment by h-vetinari** [comment]
+1 for a joint spacy-models feestock
